### ISSUE TITLE
Assorted thoughts

### ISSUE THREAD

**Issue by Jayphen** [mattpocock/figma-xstate-plugin#2]
Yo! I said I'd leave some notes here and so that's what this is. As could have been anticipated, I decided to do things other than writing code today. But I did spend da little bit of time thinking about the plugin.

Firstly, did you want to continue on from this repo or mine? It looks like we've implemented almost precisely the same thing, but I chose to just parse an object representation of the fsm instead of adding xstate as a dependency. I'm not certain that the dep is needed, but maybe there's a good reason.

Secondly, what did you actually have in mind for the plugin? So far, I've created it with a specific use-case in mind — that is, as a starting point for creating wireframes based on a finite state machine. That's essentially what we've both already done. I've also been using this as a learning exercise to improve my knowledge of fsms/state charts, because I see a lot of value in the paradigm but still lack an understanding deep enough to confidently speak or think about it.

To make this plugin more useful, it makes sense to add some support for state charts — compound states at the least.

Here's a sketch of how that may look in Figma, with each state represented by an artboard, and arrows outside the artboard bounds to show events/transitions. This is a simple example where each state has only one possible event, but the plugin should support many. Of course this makes positioning everything using Figma's API a lot more complex/fun :D  

<img width="634" alt="CleanShot 2020-02-16 at 17 33 54@2x" src="https://user-images.githubusercontent.com/329184/74608575-86a4ce00-50e2-11ea-972b-0d10ba61c977.png">

Since in a real life project the requirements/specs may change, it would also be nice if this plugin could update a Figma document with new frames while retaining the old ones if a machine is modified and re-imported.

As a stretch goal, it would be awesome if there was a two-way binding to the state chart, so you could visually update it from within Figma. I suspect David is working on a visual tool already, but allowing designers to actually build out/augment state charts from inside Figma would be a huge boon.

Anyway, those are my rather unorganised Sunday evening thoughts. Cheers!

**Comment by mattpocock** [comment]
Hey @Jayphen - thanks so much for reaching out and posting an issue. I'm so excited that you're into it. Thanks for providing so much detail.

## Xstate as a dependency?

I had a little look at your repo too, and yes, that does seem to be the main difference. I think I am keen on keeping Xstate as a dependency because it keeps the parsing logic where it belongs - in the Xstate repo. Maintaining a second FSM parser might get a bit tiring in the long run.

Also, the parsing looks quite complex when you consider all of the potential shapes that a state transition can take - `cond` clauses, `onDone`, `onError` etc. I would definitely prefer to farm that out to Xstate, which can own it and tell us if we're doing something wrong via Typescript.

## Compound States

Awesome idea. I hadn't thought about representing compound/orthogonal states, but it makes a ton of sense. Representing these states beautifully would add a lot of value. I think we should draw on `@xstate/viz` as much as we can, so that this plugin feels like a natural part of the `xstate` ecosystem.

I'll raise this as a separate issue on the repo, and we can continue the conversation in more depth there.

## Two-way binding

Again, fantastic idea. Creating an `Export screens to State Machine` flow would be incredibly useful. Imagine prototyping an idea in Figma, adding transitions, then exporting that into a state machine which can fuel e2e tests.

Xstate feels most powerful when it acts as a language to link documents and workflows together, and adding the export would be very, very cool.

Again, I'll raise this as a separate issue so we can continue chatting and organise priority.

# Problems

## Figma's lack of support for transitions

This is a biggy for me - Figma currently doesn't support changing transition attributes from plugins. This will probably drop in the future. For me, the biggest value add of this plugin will be the _transitions_ - being able to drop in a state machine, jump into the prototype, and click around will be the _oh, wow_ moment for our users. Without this, the plugin will likely feel a little flat.

Do you think we have enough of a "value add" without this feature? Or should we suspend until Figma releases it?

Thanks again for your time, @Jayphen.

**Comment by Jayphen** [comment]
Yeah, the lack of transition support is a bit of a bummer.

As it is, the plugin does pretty much what I wanted it to do in order to save me a little bit of time bootstrapping a wireframing process.

I think the two-way binding ('export state machine') would still make this more broadly useful even without transitions. This would require careful naming of frames, but I think it could be achieved.

**Comment by mattpocock** [comment]
On the two-way binding, yes - I could see that. I'll check out what you've done on your repo.

I think without transition support I'm not sure I can see a path where it's useful to my team _at the moment_. The transitions really are the big sell. I think I'll pause contributing to this repo, and I look forward to seeing what you come up with on yours.

But if Figma adds transition support, I'll be back on this like a flash. It has a lot of potential.
